// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA75FV09wY1ApLTNtPPhrNS_EcoXnWOUkg',
    appId: '1:84160145904:web:410f506eb101f5fe8e9535',
    messagingSenderId: '84160145904',
    projectId: 'demo1-abf1c',
    authDomain: 'demo1-abf1c.firebaseapp.com',
    databaseURL: 'https://demo1-abf1c-default-rtdb.firebaseio.com',
    storageBucket: 'demo1-abf1c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAYkIUxR_UXr89LP6pnRgCYyKj3wBXthc',
    appId: '1:84160145904:android:05d1d8babe309a988e9535',
    messagingSenderId: '84160145904',
    projectId: 'demo1-abf1c',
    databaseURL: 'https://demo1-abf1c-default-rtdb.firebaseio.com',
    storageBucket: 'demo1-abf1c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoZ2O7WJ2DCIiRJ7WmnZYKzxMChH9HfSQ',
    appId: '1:84160145904:ios:3c17ff3c278a58ac8e9535',
    messagingSenderId: '84160145904',
    projectId: 'demo1-abf1c',
    databaseURL: 'https://demo1-abf1c-default-rtdb.firebaseio.com',
    storageBucket: 'demo1-abf1c.appspot.com',
    iosClientId: '84160145904-8ro21irmkigjeep5ckr11upjhivojv5r.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoZ2O7WJ2DCIiRJ7WmnZYKzxMChH9HfSQ',
    appId: '1:84160145904:ios:3c17ff3c278a58ac8e9535',
    messagingSenderId: '84160145904',
    projectId: 'demo1-abf1c',
    databaseURL: 'https://demo1-abf1c-default-rtdb.firebaseio.com',
    storageBucket: 'demo1-abf1c.appspot.com',
    iosClientId: '84160145904-8ro21irmkigjeep5ckr11upjhivojv5r.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopApp',
  );
}
